### ISSUE TITLE
entire tower section is inaccurate, out of date, dead links

### ISSUE THREAD

**Issue by pchickey** [GaloisInc/ivorylang-org#1]
see numerous reports:
https://github.com/GaloisInc/ivory/issues/52
https://github.com/GaloisInc/tower/issues/10

this is sloppy and embarrassing and 100% my fault.

**Comment by AleXoundOS** [comment]
Sorry, the issue still persists. The file [tower-overview.md](https://github.com/GaloisInc/ivorylang-org/blob/master/pages/tower-overview.md) is full of broken links. And it's desirable to have a much deeper tower overview.

**Comment by podhrmic** [comment]
Fixed (at least the broken links) with #2
